sudo: required

services:
  - docker

before_install:
  - docker build -t uriinf/tools .

script:
  - ANSIBLE_RETRY_FILES_ENABLED=0 docker run --rm -it -v $(pwd)/test:/workspace uriinf/tools ansible-playbook -i /workspace/hosts /workspace/play.yml
