sudo: required

services:
  - docker

before_install:
  - docker build -t uriinf/tools .

script:
  - ANSIBLE_RETRY_FILES_ENABLED=0 docker run -it --rm -v $(pwd)/test:/workspace uriinf/tools ansible-playbook -i ./hosts play.yml
  - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/test:/workspace -w /workspace uriinf/tools terraform apply
  - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/test:/workspace -w /workspace uriinf/tools terraform destroy -force
  - rm -rf test/*.tfstate*
	- docker ps -a
  - ls -la
